name-template: 'Superalgos-v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
categories:
  - title: 'Breaking'
    label: 'type: breaking'
  - title: 'ðŸš€ New Feature'
    label: 'type: feature'
  - title: 'ðŸ› Bug Fixes'
    label: 'type: bug'
  - title: 'ðŸ§° Maintenance'
    label: 'type: maintenance'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
  - title: 'Security'
    label: 'type: security'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'

exclude-labels:
  - 'skip-changelog'