name-template: 'Superalgos-v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'Breaking'
    label: 'breaking'
  - title: '🚀 New Feature'
    label: 
      - 'feature'
      - 'improvement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'code maintenance'
  - title: 'Documentation'
    label: 
      - 'documentation'
      - 'Education Project'
  - title: 'Dependency Updates'
    label: 'dependencies'
  - title: 'Security'
    label: 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
template: |
  ### What's Changed
  $CHANGES
  ### Who participated in this release
  $CONTRIBUTORS