name: Nightly develop Binaries (dev)

on:
  schedule:
    - cron:  '20 3 * * *'

  workflow_dispatch:

jobs:
  create-release:
    if: github.repository == 'NAmorim/Superalgos'
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        run: curl "https://raw.githubusercontent.com/${{ github.repository }}/develop/package.json" -o package.json

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Get version
        id: vars
        run: echo "tag=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create nightly release
        id: create_release
        uses: viperproject/create-nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}-${{ env.date }}
          release_name: Superalgos-Beta-v${{ env.tag }} Snapshot ${{ env.date }}
          keep_num: 5
          keep_tags: false

  build-release:
    #if: github.repository == 'superalgos/superalgos'
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
        matrix:
          os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      #- name: Get current date
      #  id: date
      #  run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Get version
      #  id: vars
      #  run:  echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build/release Electron app
        # uses: samuelmeuli/action-electron-builder@v1.6.0
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          args: "-c.extraMetadata.version=${{ env.tag }}-${{ env.date }} -c build/electron-builder.json -p onTagOrDraft"

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          release: true
 

